#!/bin/sh
if test -d $1
then
	chmod a+rx $1
	echo "Directory '$1' is now made public."
elif test -f $1
then
	echo "File '$1' is now made public."
	chmod a+r $1
else
	echo "File '$1' does not exits."
fi
